version: '3'
services:
  ecoflow-mqtt:
    build: ./ecoflow-stream-ultra
    environment:
      - EF_EMAIL=dein@email.de
      - EF_PASSWORD=••••••••
      - EF_DEVICE_ID=deine_stream_ultra_id
      - MQTT_HOST=docker-symcon.smart.local
      - MQTT_PORT=1883
    restart: always
