version: '3.8'

services:
  ecoflow-mqtt:
    build: 
        context: .
        dockerfile: Dockerfile
    image: ecoflow-mqtt-debug
    container_name: ecoflow-mqtt-bridge
    restart: unless-stopped
    env_file: .env
    environment:
      # Python Output buffering für bessere Logs
      - PYTHONUNBUFFERED=1
    command: >
      --username=${ECOFLOW_USERNAME}
      --password=${ECOFLOW_PASSWORD}
      --device-sn=${DEVICE_SN}
      --mqtt-host=${MQTT_HOST}
      --mqtt-port=${MQTT_PORT}
      --mqtt-username=${MQTT_USERNAME}
      --mqtt-password=${MQTT_PASSWORD}
    networks:
      - ecoflow
    # Log-Rotation für bessere Performance
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  ecoflow:
    driver: bridge



